# GoReleaser configuration for automated builds
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: arcpoint-mcp
    binary: arcpoint-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: arcpoint-mcp
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: arcpoint-ai
    name: arcpoint-mcp
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: arcpoint-mcp
    repository:
      owner: arcpoint-ai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Official MCP client for Arcpoint"
    homepage: "https://arcpoint.ai"
    license: "MIT"
    install: |
      bin.install "arcpoint-mcp"
    test: |
      system "#{bin}/arcpoint-mcp", "--version"

